// <auto-generated />
namespace Dictionary.DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addMessage : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMessage));
        
        string IMigrationMetadata.Id
        {
            get { return "202403202004311_addMessage"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
